# CTF专用配置
title: "CTF Crypto Solutions"
url: "https://102300671.github.io"  # 强制HTTPS
baseurl: ""  # 修正基础路径

# 安全增强
csp:
  default-src: "'self'"
  script-src: "'self' https://cdnjs.cloudflare.com 'unsafe-eval'"
  style-src: "'self' 'unsafe-inline'"
  img-src: "*"

# 数学公式优化
kramdown:
  math_engine: mathjax
  math_engine_opts: 
    preview: false
    mtextFontInherit: true

# 构建加速
exclude:
  - "*.txt"
  - "test/"
  - "drafts/"
  - "venv/"

# CTF分类系统
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "ctf"
      category: "Crypto"
      difficulty: "Medium"

# 插件增强
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
